// music-app/src/app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import AuthButton from "@/app/components/AuthButton";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Music App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				{/* Navbar */}
				<nav className="bg-white shadow-md">
					<div className="max-w-7xl mx-auto px-2 py-4 flex items-center justify-between">
						<Link
							href="/"
							className="text-xl font-bold text-[#FF8200] hover:text-orange-800 transition"
						>
							Music Education App
						</Link>
						<div className="flex items-center space-x-6">
						<AuthButton />
						</div>
					</div>
				</nav>

				{/* Page Content */}
				<main>
					{children}
				</main>
			</body>
		</html>
	);
}