import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import SessionProviderWrapper from "./sessionproviderwrapper"; // import client wrapper

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Music App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				{/* Navbar */}
				<nav className="bg-white shadow-md">
					<div className="max-w-7xl mx-auto px-2 py-4 flex items-center justify-between">
						<Link
							href="/"
							className="text-xl font-bold text-indigo-600 hover:text-indigo-800 transition"
						>
							Music Education App
						</Link>
						<div className="flex space-x-6">
							<Link href="/" className="text-gray-700 hover:text-indigo-600 transition">
								Home
							</Link>
							<Link href="/briform" className="text-gray-700 hover:text-indigo-600 transition">
								Briform
							</Link>
							<Link href="/player" className="text-gray-700 hover:text-indigo-600 transition">
								Player
							</Link>
						</div>
					</div>
				</nav>

				{/* Page Content */}
				<main>
					<SessionProviderWrapper>{children}</SessionProviderWrapper>
				</main>
			</body>
		</html>
	);
}